pipeline {
    agent { docker { image 'node:6.3' } }
    stages {
        stage('build') {
            steps {
                echo 'Hi world'
                sh 'npm --version'
            }
        }
    }
}
