pipeline {
    agent { docker { image 'node:8.11.2' } }
    stages {
        stage('build') {
            steps {
                echo 'Hi world'
                sh 'npm --version'
            }
        }
    }
}
